---
before_install:
  - sudo apt-get install -qq augeas-tools augeas-lenses libaugeas-dev
  - sudo wget -O /usr/share/augeas/lenses/sssd.aug https://raw.githubusercontent.com/hercules-team/augeas/master/lenses/sssd.aug
language: ruby
script: "fakeroot bundle exec rake spec"
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2

env:
  - PUPPET_VERSION="~> 3.6.2"
  - PUPPET_VERSION="~> 3.7.0"
  - PUPPET_VERSION="~> 3.8.0"
  - PUPPET_VERSION="~> 4.0.0"
  - PUPPET_VERSION="~> 4.1.0"
  - PUPPET_VERSION="~> 4.2.0"
  - PUPPET_VERSION="~> 4.3.0"
  - PUPPET_VERSION="~> 4.4.0"
  - PUPPET_VERSION="~> 4.5.0"

matrix:
  exclude:
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.1.0"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 4"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 4"
  
